init project5:change yml3 & add clone project

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,10 +59,10 @@ jobs:
             cd /home/ec2-user/Docker/ # Navigate to the project directory
 
             # Check if the docker-compose.yml file exists
-            if [ ! -f docker-compose.yml ]; then
-              echo "Error: docker-compose.yml not found!"
-              exit 1
-            fi
+            #if [ ! -f docker-compose.yml ]; then
+            #  echo "Error: docker-compose.yml not found!"
+            #  exit 1
+            #fi
 
               git clone git@github.com:darktend/project1.git
               cd project1
